import { Fragment, useRef } from 'react';
import { View } from 'react-native';
import { ModalManager } from '@walless/gui';
import type { AppProps } from 'next/app';
import Head from 'next/head';

import '../globals.css';

export default function App({ Component, pageProps }: AppProps) {
	const containerRef = useRef<View>(null);

	return (
		<Fragment>
			<Head>
				<title>glhf.world</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<View ref={containerRef}>
				<Component {...pageProps} />
			</View>
			<ModalManager />
		</Fragment>
	);
}
